<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/bootstrap.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/font-awesome.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/meanmenu.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/owl.carousel.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/owl.theme.default.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/nivo-slider.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/icofont.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/material-design-iconic-font.min.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/magnific-popup.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/animate.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/shortcode/shortcodes.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/style.css">
<link rel="stylesheet" href="{{asset('assets/frontend')}}/css/responsive.css">